export const API_ENDPOINTS = {
    auth: {
        login: '/api/auth/login',
        logout: '/api/auth/logout',
        register: '/api/auth/register',
        refresh: '/api/auth/refresh',
        forgotPassword: '/api/auth/forgot-password',
        resetPassword: '/api/auth/reset-password',
        verifyEmail: '/api/auth/verify-email',
        mfaVerify: '/api/auth/2fa/verify',
    },
    clinics: {
        list: '/api/clinics',
        create: '/api/clinics',
        byId: (id: number | string) => `/api/clinics/${id}`,
        byCity: (city: string) => `/api/clinics/city/${city}`,
        update: (id: number) => `/api/clinics/${id}`,
        delete: (id: number) => `/api/clinics/${id}`,
        vetAvailableSlots: (clinicId: number, vetUserId: number) =>
            `/api/clinics/${clinicId}/vets/${vetUserId}/available-slots`,
    },
    vets: {
        list: '/api/vets',
        create: '/api/vets',
        byId: (id: number) => `/api/vets/${id}`,
        byClinic: (clinicId: number) => `/api/vets/clinic/${clinicId}`,
        update: (id: number) => `/api/vets/${id}`,
        delete: (id: number) => `/api/vets/${id}`,
        me: '/api/vets/me',
        meVisits: '/api/vets/me/visits',
        meVisitsUpcoming: '/api/vets/me/visits/upcoming',
        meVisitConfirm: (id: number) => `/api/vets/me/visits/${id}/confirm`,
        meVisitMedicalData: (id: number) => `/api/vets/me/visits/${id}/medical-data`,
    },
    animals: {
        list: '/api/animals',
        create: '/api/animals',
        byId: (id: number) => `/api/animals/${id}`,
        byOwner: (ownerId: number) => `/api/animals/owner/${ownerId}`,
        update: (id: number) => `/api/animals/${id}`,
        delete: (id: number) => `/api/animals/${id}`,
        visits: (animalId: number) => `/api/animals/${animalId}/visits`,
    },
    visits: {
        create: '/api/visits',
        byId: (id: number) => `/api/visits/${id}`,
        cancel: (id: number) => `/api/visits/${id}/cancel`,
        prescription: (id: number) => `/api/visits/${id}/prescription`,
    },
    owners: {
        me: '/api/owners/me',
        meVisits: '/api/owners/me/visits',
        meVisitsUpcoming: '/api/owners/me/visits/upcoming',
        mePhone: '/api/owners/me/phone',
        mePassword: '/api/owners/me/password',
        meAddress: '/api/owners/me/address',
        meDeviceTokens: '/api/owners/me/device-tokens',
    },
    warehouse: {
        stock: '/api/warehouse/stock',
        stockById: (id: number) => `/api/warehouse/stock/${id}`,
        stockByWarehouse: (warehouseId: number) => `/api/warehouse/stock/warehouse/${warehouseId}`,
        stockLowStock: '/api/warehouse/stock/low-stock',
        workerMe: '/api/warehouse-workers/me',
    },
    orders: {
        list: '/api/orders',
        create: '/api/orders',
        updateStatus: (id: number) => `/api/orders/${id}/status`,
    },
    admin: {
        users: '/api/admin/users',
        userById: (id: number) => `/api/admin/users/${id}`,
        logs: '/api/admin/logs',
        logStats: '/api/admin/logs/stats',
    },
} as const;
